// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB21P10mKBvtHSE8e_NluudkRk3bgqmNv0',
    appId: '1:831052690195:web:553591168a05b5e3fea0e6',
    messagingSenderId: '831052690195',
    projectId: 'to-do-app-cb10e',
    authDomain: 'to-do-app-cb10e.firebaseapp.com',
    storageBucket: 'to-do-app-cb10e.firebasestorage.app',
    measurementId: 'G-VWLJSQRP3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhfcYn2-AZCh_ZkNVHkoimSY91GgAx5rQ',
    appId: '1:831052690195:android:b500610117568e7cfea0e6',
    messagingSenderId: '831052690195',
    projectId: 'to-do-app-cb10e',
    storageBucket: 'to-do-app-cb10e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-RgfCFVEkV0Jkywmu6fpiKQU4Kkq2po',
    appId: '1:831052690195:ios:76cb94478ed9faf9fea0e6',
    messagingSenderId: '831052690195',
    projectId: 'to-do-app-cb10e',
    storageBucket: 'to-do-app-cb10e.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-RgfCFVEkV0Jkywmu6fpiKQU4Kkq2po',
    appId: '1:831052690195:ios:76cb94478ed9faf9fea0e6',
    messagingSenderId: '831052690195',
    projectId: 'to-do-app-cb10e',
    storageBucket: 'to-do-app-cb10e.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB21P10mKBvtHSE8e_NluudkRk3bgqmNv0',
    appId: '1:831052690195:web:6cf45b29b1444c4bfea0e6',
    messagingSenderId: '831052690195',
    projectId: 'to-do-app-cb10e',
    authDomain: 'to-do-app-cb10e.firebaseapp.com',
    storageBucket: 'to-do-app-cb10e.firebasestorage.app',
    measurementId: 'G-ZD58FBJ3Z8',
  );
}
